language: ruby

cache: bundler

sudo: required
before_script: "unset _JAVA_OPTIONS"
before_install: gem install bundler -v '<2'

rvm:
  - 2.5.3
  - 2.6.0
  - 2.7.1
  - jruby-9.2.5.0
  - jruby-head
  - ruby-head

matrix:
  include:
    - rvm: 2.7.1
      script: bundle exec rake test_isolated
    - rvm: 2.7.1
      script: bundle exec rake rubocop
  allow_failures:
    - rvm: jruby-9.2.5.0
    - rvm: jruby-head
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#rails-contrib"
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "bJyiK4EXGfm0EhAId/QqIEdhPCx8BjxUKvx1h0+wgrsUm8BDoEN7tg2wqoGWU2KfzqLdx77wZVQXbmksOgmNcMGKJed5uNNMpAG4B+AQYTEX0odFRgOZKdkMtypga9CNIkKVgeSKhd6BY+g2AV6wvJ0Jq056uXpGkqK5OEFOpQc="
