install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

cache:
  - vendor/bundle

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake

environment:
  matrix:
    - RUBY_VERSION: 26-x64
    - RUBY_VERSION: 25-x64

